---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(rvest)
```

```{r}
# gathering data about coaches from: https://www.pro-football-reference.com/teams/crd/coaches.htm
# converting typical team ID's to their PFR page ID
nfl_to_pfr <- c(
  ARI = "CRD",
  ATL = "ATL",
  BAL = "RAV",
  BUF = "BUF",
  CAR = "CAR",
  CHI = "CHI",
  CIN = "CIN",
  CLE = "CLE",
  DAL = "DAL",
  DEN = "DEN",
  DET = "DET",
  GB  = "GNB",
  HOU = "HTX",
  IND = "CLT",
  JAX = "JAX",
  KC  = "KAN",
  LAC = "SDG",
  LAR = "RAM",
  LV  = "RAI",
  MIA = "MIA",
  MIN = "MIN",
  NE  = "NWE",
  NO  = "NOR",
  NYG = "NYG",
  NYJ = "NYJ",
  PHI = "PHI",
  PIT = "PIT",
  SEA = "SEA",
  SF  = "SFO",
  TB  = "TAM",
  TEN = "OTI",
  WSH = "WAS"
)

# Example usage:
nfl_to_pfr["GB"]   # returns "GNB"
nfl_to_pfr["NE"]   # returns "NWE"

```

```{r}

# initialize coaches dataframe
coaches <- data.frame()


# parse through all teams
for(team in nfl_to_pfr){
  # create link to PFR coaches page for the team
  link <- paste0('https://www.pro-football-reference.com/teams/', tolower(team), '/coaches.htm')

  # get table data for team
  team_coaches <- read_html(link) %>%
    html_node('table#coaches_year') %>%
    html_table(fill = TRUE)
  
  # get headers for the table
  team_headers <- read_html(link)  %>% 
    html_nodes('table#coaches_year thead tr th') %>% 
    html_text()
  
  # remove redundant headers
  team_headers <- team_headers[-(1:4)]
  
  # rename columns
  colnames(team_coaches)<- team_headers[1:length(team_headers)]
  
  # create "team" column
  team_coaches$team <- names(nfl_to_pfr)[which(nfl_to_pfr == team)]
  
  # add team's coaching history to primary dataframe
  coaches <- coaches %>% 
    bind_rows(team_coaches)
}

all_coaches <- coaches %>% 
  filter(Year != "Year") %>%  # removing rows with header information that stuck with the df
  mutate(Year = ifelse(Year == "", lag(Year), Year)) %>%  # accounting for several coaches in the same year
  mutate(Year = ifelse(Year == "", lag(Year), Year)) %>%  # doing it again for 3 coaches
  mutate(Year = ifelse(Year == "", lag(Year), Year))  # some teams had 4! wow!
```

```{r}
dim(all_coaches) # we have 2394 coaches and 14 columns
min(all_coaches$Year) # data goes back to 1920
all_coaches %>% group_by(team, Year) %>% count %>% arrange(desc(n)) %>% head(1) %>% pull(n) # most HC in a season ever is 4, held by the 1961 Cardinals, who had three HC at once after firing their initial HC.

```


```{r}
write.csv(all_coaches, "../../data/raw/coaches.csv")
```

