---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(nflfastR)
library(nflreadr)
```

```{r}
schedule <- load_schedules(2015:2025)
coaches <- read.csv("../../data/raw/coaches.csv")

```

```{r}
home_games <- schedule %>% 
  select(game_id, home_team, result, total, overtime, season, game_type, week, weekday, gametime, home_coach, location, div_game, away_rest, home_rest) %>% 
  mutate(rest_gap = home_rest - away_rest) %>% 
  select(-away_rest, -home_rest) %>% 
  filter(location != "Neutral") %>% 
  rename(team = home_team, coach = home_coach) %>% 
  mutate(side = "home")

away_games <- schedule %>% 
  select(game_id, away_team, result, total, overtime, season, game_type, week, weekday, gametime, away_coach, location, div_game, away_rest, home_rest) %>% 
  mutate(rest_gap = away_rest - home_rest) %>% 
  mutate(result = -result) %>% 
  select(-away_rest, -home_rest) %>% 
  filter(location != "Neutral") %>% 
  rename(team = away_team, coach = away_coach) %>% 
  mutate(side = "away")

neutral_games1 <- schedule %>% 
  select(game_id, home_team, result, total, overtime, season, game_type, week, weekday, gametime, home_coach, location, div_game, away_rest, home_rest) %>% 
  mutate(rest_gap = home_rest - away_rest) %>% 
  select(-away_rest, -home_rest) %>% 
  filter(location == "Neutral") %>% 
  rename(team = home_team, coach = home_coach) %>% 
  mutate(side = "home")

neutral_games2 <- schedule %>% 
  select(game_id, away_team, result, total, overtime, season, game_type, week, weekday, gametime, away_coach, location, div_game, away_rest, home_rest) %>% 
  mutate(rest_gap = away_rest - home_rest) %>% 
  mutate(result = -result) %>% 
  select(-away_rest, -home_rest) %>% 
  filter(location == "Neutral") %>% 
  rename(team = away_team, coach = away_coach) %>% 
  mutate(side = "away")

all_games <- home_games %>% 
  bind_rows(away_games, neutral_games1, neutral_games2) %>% 
  arrange(game_id)
```

```{r}
team_records <- all_games %>%
  mutate(side = ifelse(location == "Neutral", "neutral", side)) %>% 
  group_by(season, team) %>% 
  mutate(home_wins = sum(result > 0 & side == "home" & game_type == "REG"),
         home_losses = sum(result < 0 & side == "home" & game_type == "REG"),
         home_ties = sum(result == 0 & side == "home" & game_type == "REG"),
         away_wins = sum(result > 0 & side == "away" & game_type == "REG"),
         away_losses = sum(result < 0 & side == "away" & game_type == "REG"),
         away_ties = sum(result == 0 & side == "away" & game_type == "REG"),
         neutral_wins = sum(result > 0 & side == "neutral" & game_type == "REG"),
         neutral_losses = sum(result < 0 & side == "neutral" & game_type == "REG"),
         neutral_ties = sum(result == 0 & side == "neutral" & game_type == "REG"),
         one_score_wins = sum(result > 0 & result < 9 & game_type == "REG"),
         one_score_losses = sum(result < 0 & result > -9 & game_type == "REG"),
         div_wins = sum(result > 0 & div_game == 1 & game_type == "REG"),
         div_losses = sum(result < 0 & div_game == 1 & game_type == "REG"),
         div_ties = sum(result == 0 & div_game == 1 & game_type == "REG"),
         rest_adv_wins = sum(result > 0 & rest_gap >= 2 & game_type == "REG"),
         rest_adv_losses = sum(result < 0 & rest_gap >= 2 & game_type == "REG"),
         rest_adv_ties = sum(result == 0 & rest_gap >= 2 & game_type == "REG"),
         rest_disadv_wins = sum(result > 0 & rest_gap <= -2 & game_type == "REG"),
         rest_disadv_losses = sum(result < 0 & rest_gap <= -2 & game_type == "REG"),
         rest_disadv_ties = sum(result == 0 & rest_gap <= 2 & game_type == "REG"),
         ot_wins = sum(result > 0 & overtime == 1 & game_type == "REG"),
         ot_losses = sum(result < 0 & overtime == 1 & game_type == "REG"),
         ot_ties = sum(result == 0 & overtime == 1 & game_type == "REG"),
         playoff_wins = sum(result > 0 & game_type != "REG"),
         playoff_losses = sum(result < 0 & game_type != "REG")) %>% 
  arrange(game_id) %>% 
  mutate(round_reached = last(game_type),
         made_playoffs = round_reached != "REG") %>% 
  select(season, team, 16:last_col()) %>% 
  distinct() %>% 
  mutate(team = case_when(
    team == "OAK" ~ "LV",
    team == "SD" ~ "LAC", 
    team == "STL" ~ "LA",
    team == "WAS" ~ "WSH",
    .default = team
  )) %>% 
  mutate(team = ifelse(team == "LA", "LAR", team)) %>% 
  arrange(team, season) %>% 
  left_join(coaches %>% select(season = Year, team, coach = Coach, offense = Offense, defense = Defense)) %>% 
  mutate(reg_wins = home_wins + away_wins + neutral_wins,
         reg_losses = home_losses + away_losses + neutral_losses,
         reg_ties = home_ties + away_ties + neutral_ties,
         won_sb = made_playoffs & playoff_losses == 0) %>% 
  select(season, team, coach, offense, defense, reg_wins, reg_losses, reg_ties, everything())
```

```{r}
write.csv(team_records, "../../data/processed/team_records.csv")
```

