---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(nflfastR)
library(nflreadr)
library(Matrix)
library(stringr)
```

```{r}
year <- 2023

data <- load_pbp(year)

part <- load_participation(year)

pbp22 <- data %>%
  inner_join(
    part,
    by = c("game_id" = "nflverse_game_id", "play_id")
  )


pbp22 <- pbp22 %>%
  mutate(
    off_list = str_split(offense_players, ";"),
    def_list = str_split(defense_players, ";")
  )
  
```

```{r}
apm_long <- pbp22 %>%
  select(game_id, play_id, epa, off_list, def_list) %>%
  unnest(off_list) %>%
  mutate(
    nfl_id = off_list,
    sign = 1
  ) %>%
  select(game_id, play_id, epa, nfl_id, sign) %>%
  bind_rows(
    pbp22 %>%
      select(game_id, play_id, epa, def_list) %>%
      unnest(def_list) %>%
      mutate(
        nfl_id = def_list,
        sign = -1
      ) %>%
      select(game_id, play_id, epa, nfl_id, sign)
  )

```


```{r}
apm_long %>%
  count(game_id, play_id) %>%
  count(n)

```

```{r}
player_index <- apm_long %>%
  distinct(nfl_id) %>%
  arrange(nfl_id) %>%
  mutate(player_idx = row_number())

apm_long <- apm_long %>%
  left_join(player_index, by = "nfl_id")

play_index <- apm_long %>%
  distinct(game_id, play_id) %>%
  arrange(game_id, play_id) %>%
  mutate(play_idx = row_number())

apm_long <- apm_long %>%
  left_join(play_index, by = c("game_id", "play_id"))

X <- sparseMatrix(
  i = apm_long$play_idx,
  j = apm_long$player_idx,
  x = apm_long$sign,
  dims = c(nrow(play_index), nrow(player_index))
)

y <- pbp22 %>%
  distinct(game_id, play_id, epa) %>%
  arrange(game_id, play_id) %>%
  pull(epa)

```

```{r}
stan_code <- "
data {
  int<lower=1> N;               // number of plays
  int<lower=1> P;               // number of players
  matrix[N, P] X;               // design matrix
  vector[N] y;                  // EPA
}

parameters {
  real alpha;                   // baseline EPA
  vector[P] beta;               // player APM
  real<lower=0> sigma;          // noise
  real<lower=0> tau;            // shrinkage
}

model {
  // Priors
  alpha ~ normal(0, 0.5);
  tau   ~ normal(0, 0.5);
  beta  ~ normal(0, tau);
  sigma ~ normal(0, 1);

  // Likelihood
  y ~ normal(alpha + X * beta, sigma);
}
"

```

```{r}
library(rstan)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

stan_model <- stan_model(model_code = stan_code)

```

```{r}
stan_data <- list(
  N = nrow(X),
  P = ncol(X),
  X = as.matrix(X),
  y = y
)

fit <- sampling(
  stan_model,
  data = stan_data,
  chains = 4,
  iter = 1000,
  warmup = 500,
  refresh = 10,        # <-- prints every 10 iterations
  verbose = TRUE,      # <-- extra diagnostics
  control = list(adapt_delta = 0.9)
)


```

```{r}
post <- rstan::extract(fit)
beta_mean <- colMeans(post$beta)
beta_sd   <- apply(post$beta, 2, sd)

player_apm <- player_index %>%
  mutate(
    apm = beta_mean,
    apm_sd = beta_sd,
    apm_per_play = apm / 11
  )

```

```{r}
players <- load_rosters(year)
```

```{r}
player_apm_names <- player_apm %>% 
  left_join(players %>% select(nfl_id = gsis_id, full_name, team, position), by = c("nfl_id")) %>% 
  arrange(desc(apm))
```

```{r}
write.csv(player_apm_names, file = paste0("../../data/processed/player_apm", year, ".csv"))
```


```{r}
player_apm_names %>% 
  group_by(position) %>% 
  summarise(apm = mean(apm)) %>% 
  arrange(desc(apm))
```

```{r}
player_apm_names %>% 
  filter(position == "RB") %>% 
  arrange(desc(apm_per_play))
```

